// HemoAtlas v6 — perfil refinado e edição de submissão com selects
window.HemoProfile = (() => {
  const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  let uploads = [], reports = [], favCount = 0;
  const OPTS = {
    material:['Sangue periférico','Medula óssea','Aspirado medular','Esfregaço'],
    lineage:['Eritroide','Mieloide','Linfoide','Megacariocítica'],
    finding_type:['Célula normal','Variante morfológica','Alteração patológica','Inclusão citoplasmática','Parasita'],
    staining:['May-Grünwald-Giemsa','Wright-Giemsa','Panótico rápido','Giemsa','Outro'],
    magnification:['400x','600x','1000x','Outro'],
    diagnosis:['Morfologia normal','Anemia ferropriva','Anemia megaloblástica','Leucemia mieloide aguda','Leucemia linfoblástica aguda','Síndrome mielodisplásica','Mieloma múltiplo','Malária','Outro']
  };
  function select(name, value){ return `<select name="${name}" class="hemo-select">${OPTS[name].map(v=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`; }
  async function loadUploads(user){ if(!HemoSupabase.isConfigured()) return []; const {data,error}=await HemoSupabase.client.from('images').select('*, image_categories(name)').eq('author_id',user.id).order('created_at',{ascending:false}); if(error){HemoApp.toast(error.message,'error'); return []} return HemoApp.normalizeImages(data||[]); }
  async function loadReports(user){ if(!HemoSupabase.isConfigured()) return []; const {data,error}=await HemoSupabase.client.from('reports').select('*').or(`reporter_id.eq.${user.id},reporter_email.eq.${user.email}`).order('created_at',{ascending:false}); return error?[]:(data||[]); }
  async function loadFavCount(user){ if(!HemoSupabase.isConfigured()) return 0; const {count}=await HemoSupabase.client.from('favorites').select('*',{count:'exact',head:true}).eq('user_id',user.id); return count||0; }
  function uploadItem(i){ const canEdit=['revision_required','pending'].includes(i.status)&&!i.privacy_hold; return `<article class="profile-list-item"><div><strong>${esc(i.code||'HEM-NOVO')} — ${esc(i.title)}</strong><p>${esc(i.review_note||i.rejection_reason||i.description||'Sem observações da curadoria.')}</p><small>${esc(i.material||'-')} · ${esc(i.finding_type||'-')}</small></div><div class="profile-actions">${HemoApp.badge(i.status)}${canEdit?`<button class="hemo-btn hemo-btn-secondary" onclick="HemoProfile.openEditUpload('${esc(i.id)}')">Editar</button>`:''}</div></article>`; }
  function reportItem(r){ return `<article class="profile-list-item"><div><strong>${esc(r.reason)}</strong><p>${esc(r.description||'-')}</p><small>${HemoApp.fmtDate(r.created_at)}</small></div><div>${HemoApp.badge(r.status)}</div></article>`; }
  function render(profile,user){ const adjustments=uploads.filter(i=>i.status==='revision_required'||i.review_note||i.rejection_reason); const box=HemoApp.q('#profileBox'); if(!box)return; box.innerHTML=`<section class="profile-layout profile-v6"><aside class="profile-card hemo-card"><div class="profile-avatar">${esc((profile.full_name||user.email||'U')[0]).toUpperCase()}</div><h2>${esc(profile.full_name||profile.email||user.email||'Usuário')}</h2><p>${esc(profile.email||user.email||'')}</p><div class="profile-meta-pills">${HemoApp.badge(profile.role||'user')}<span class="hemo-badge bg-slate-100 text-slate-600">${esc(profile.institution||'Sem instituição')}</span></div><dl class="profile-mini-stats"><div><dt>Uploads</dt><dd>${uploads.length}</dd></div><div><dt>Reports</dt><dd>${reports.length}</dd></div><div><dt>Favoritos</dt><dd>${favCount}</dd></div></dl><button class="hemo-btn hemo-btn-danger mt-5" onclick="HemoAuth.logout()">Sair</button></aside><section class="profile-main"><div class="profile-section"><div class="section-title-row"><h3>Meus uploads</h3><span>${uploads.length}</span></div>${uploads.length?uploads.map(uploadItem).join(''):HemoApp.empty('Nenhuma submissão encontrada.')}</div><div class="profile-section"><div class="section-title-row"><h3>Solicitações de ajuste</h3><span>${adjustments.length}</span></div><p class="profile-help">Quando a curadoria solicitar correção, edite a submissão. Ao salvar, ela volta para aprovação.</p>${adjustments.length?adjustments.map(uploadItem).join(''):HemoApp.empty('Nenhuma solicitação de ajuste no momento.')}</div><div class="profile-section"><div class="section-title-row"><h3>Meus reports</h3><span>${reports.length}</span></div>${reports.length?reports.map(reportItem).join(''):HemoApp.empty('Nenhum report enviado.')}</div></section></section>`; }
  function openEditUpload(id){ const i=uploads.find(x=>x.id===id); if(!i)return; HemoApp.q('#editUploadModal')?.remove(); document.body.insertAdjacentHTML('beforeend', `<div id="editUploadModal" class="modal-backdrop show"><div class="modal-panel max-w-3xl p-5"><div class="modal-head"><div><p class="hemo-label">Correção de submissão</p><h2>${esc(i.code||'HEM-NOVO')} — ${esc(i.title)}</h2><p>Ao salvar, a imagem voltará para curadoria como pendente.</p></div><button class="hemo-btn hemo-btn-secondary" data-close>Fechar</button></div><form id="editUploadForm" class="admin-form-grid mt-5"><label class="full"><span class="hemo-label">Título</span><input name="title" class="hemo-input" required value="${esc(i.title)}"></label><label class="full"><span class="hemo-label">Descrição morfológica</span><textarea name="description" class="hemo-textarea" required>${esc(i.description||'')}</textarea></label><label><span class="hemo-label">Material</span>${select('material',i.material)}</label><label><span class="hemo-label">Linhagem</span>${select('lineage',i.lineage)}</label><label><span class="hemo-label">Tipo de achado</span>${select('finding_type',i.finding_type)}</label><label><span class="hemo-label">Coloração</span>${select('staining',i.staining)}</label><label><span class="hemo-label">Ampliação</span>${select('magnification',i.magnification)}</label><label><span class="hemo-label">Diagnóstico</span>${select('diagnosis',i.diagnosis)}</label><button class="hemo-btn hemo-btn-primary full">Salvar e reenviar para aprovação</button></form></div></div>`); const modal=HemoApp.q('#editUploadModal'); modal.addEventListener('click',e=>{if(e.target.matches('[data-close]')||e.target===modal)modal.remove()}); HemoApp.q('#editUploadForm').addEventListener('submit',async e=>{ e.preventDefault(); const fd=new FormData(e.target); const patch={ title:fd.get('title'), description:fd.get('description'), material:fd.get('material'), lineage:fd.get('lineage'), finding_type:fd.get('finding_type'), staining:fd.get('staining'), magnification:fd.get('magnification'), diagnosis:fd.get('diagnosis'), status:'pending', visibility:'private', privacy_hold:false, review_note:null, rejection_reason:null }; const {error}=await HemoSupabase.client.from('images').update(patch).eq('id',id); if(error) return HemoApp.toast(error.message,'error'); HemoApp.toast('Submissão atualizada e reenviada para curadoria.'); modal.remove(); setTimeout(()=>location.reload(),600); }); }
  async function init(){ const box=HemoApp.q('#profileBox'); if(!box)return; box.innerHTML=HemoApp.loading('Carregando perfil...'); await HemoAuth.requireAuth(); const [u,r,f]=await Promise.all([loadUploads(HemoAuth.user),loadReports(HemoAuth.user),loadFavCount(HemoAuth.user)]); uploads=u; reports=r; favCount=f; render(HemoAuth.profile||{},HemoAuth.user||{}); }
  document.addEventListener('DOMContentLoaded', init);
  return {openEditUpload};
})();
